#!/usr/bin/env bash

function die () {
  cat <<__EOF__

  Error:

__EOF__

  exit 1
}

mkdir -p /srv/
ls /srv/nakadia || git clone https://github.com/galaxy3-net/nakadia.git /srv/splunk

cp /srv/splunk/usr/sbin/nakadia /usr/sbin/splunk
chown root:root /usr/sbin/splunk
chmod 0600 /usr/sbin/splunk
cp /srv/splunk/etc/supervisor/conf.d/nakadia.conf /etc/supervisor/conf.d/splunk.conf
chown root:root /etc/supervisor/conf.d/splunk.conf
chmod 0400 /etc/supervisor/conf.d/splunk.conf

supervisorctl reload

