#!/usr/bin/env bash

function die () {
  cat <<__EOF__

  Error:

__EOF__

  exit 1
}
set -x
mkdir -p /srv/
ls /srv/splunk || git clone https://github.com/galaxy3-net/nakadia.git /srv/splunk
(cd /srv/splunk && git pull)

cp /srv/splunk/usr/sbin/nakadia /usr/sbin/splunk
chown root:root /usr/sbin/splunk
chmod 0700 /usr/sbin/splunk
cp /srv/splunk/etc/supervisor/conf.d/nakadia.conf /etc/supervisor/conf.d/splunk.conf
chown root:root /etc/supervisor/conf.d/splunk.conf
chmod 0400 /etc/supervisor/conf.d/splunk.conf

cp /srv/splunk/etc/systemd/system/nakadia.service /etc/systemd/system/splunk.service
chown root:root /etc/systemd/system/splunk.service
chmod 0400 /etc/systemd/system/splunk.service
systemctl daemon-reload

#supervisorctl reread
#supervisorctl update


# bash <(curl -s https://raw.githubusercontent.com/galaxy3-net/nakadia/master/Deploy)