#!/usr/bin/env bash

exec | tee -a /var/log/named_startup.log
exec 2>&1

CONTAINER_NAME=splunk
CONTAINER_IMAGE=splunk/splunk:latest

function start () {
    docker pull ${CONTAINER_IMAGE}
	sudo -E docker run -d --name ${CONTAINER_NAME} \
	  -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=cybersecurity" \
		-p 10.55.55.6:8000:8000/tcp \
		-p 10.55.55.6:9001:9001/udp \
		${CONTAINER_IMAGE}
}

cd /repos/bind/Docker
make pull

ifconfig eth1:2 10.55.55.6 netmask 255.255.255.0 up

container-rm ${CONTAINER_NAME}
start
container-alive-monitor ${CONTAINER_NAME}

#  docker run -d -p 8000:8000 -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=<password>" --name splunk splunk/splunk:latest