#!/usr/bin/env bash

exec | tee -a /var/log/nakadia_startup.log
exec 2>&1

CONTAINER_NAME=splunk
CONTAINER_IMAGE=splunk/splunk:latest

function start () {
    mkdir -p /tmp/splunk/{etc,var}
    docker pull ${CONTAINER_IMAGE}
	sudo -E docker run -d --name ${CONTAINER_NAME} \
    --mount type=bind,source=/tmp/splunk/etc,target=/opt/splunk/etc \
    --mount type=bind,source=/tmp/splunk/var,target=/opt/splunk/var \
    --mount type=bind,source=/Downloads,target=/Downloads \
	  -e "SPLUNK_START_ARGS=--accept-license" \
	  -e "SPLUNK_PASSWORD=cybersecurity" \
	  -e "SPLUNK_USERNAME=admin" \
		-p 8000:8000/tcp \
		${CONTAINER_IMAGE}

#		-p 10.55.55.6:8065:8065/tcp \
#		-p 10.55.55.6:8088:8088/tcp \
#		-p 10.55.55.6:8089:8089/tcp \
#		-p 10.55.55.6:8191:8191/tcp \
#		-p 10.55.55.6:9887:9887/tcp \
#		-p 10.55.55.6:9997:9997/tcp \
#		-p 10.55.55.6:9001:9001/udp \

}

function load_data () {
  docker exec -i --user splunk splunk /bin/bash -c "bin/splunk add monitor /Downloads/splunk"
}

function wait_on_startup () {

   sleep 120
#  until docker exec --user splunk splunk /bin/bash -c "bin/splunk status" | grep 'splunk helpers are running22'
#  do
#    echo waiting on splunk
#    sleep 10
#  done
}

cd /repos/bind/Docker
make pull

#ifconfig eth1:2 10.55.55.6 netmask 255.255.255.0 up

systemctl stop docker
systemctl start docker

container-rm ${CONTAINER_NAME}
start
wait_on_startup
load_data
container-alive-monitor ${CONTAINER_NAME}


#  docker run -d -p 8000:8000 -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=<password>" --name splunk splunk/splunk:latest