#!/usr/bin/env bash

exec | tee -a /var/log/nakadia_startup.log
exec 2>&1

CONTAINER_NAME=splunk
CONTAINER_IMAGE=splunk/splunk:latest

function start () {
  mkdir -p /tmp/splunk/{etc,var}
  docker pull ${CONTAINER_IMAGE}

	sudo -E docker run -t --name ${CONTAINER_NAME} \
    --mount type=bind,source=/tmp/splunk/etc,target=/opt/splunk/etc \
    --mount type=bind,source=/tmp/splunk/var,target=/opt/splunk/var \
    --mount type=bind,source=/var/log/,target=/var/log/nakadia/ \
    --mount type=bind,source=/Downloads,target=/Downloads \
    --mount type=bind,source=/repos,target=/repos \
	  -e "SPLUNK_START_ARGS=--accept-license" \
	  -e "SPLUNK_PASSWORD=cybersecurity" \
	  -e "SPLUNK_USERNAME=admin" \
		-p 8000:8000/tcp \
		${CONTAINER_IMAGE} || sudo docker start -a -i ${CONTAINER_NAME}

}

function load_data () {
  docker exec -i --user splunk splunk /bin/bash -c "bin/splunk add monitor /Downloads/splunk"
}

function wait_on_startup () {

   sleep 120
#  until docker exec --user splunk splunk /bin/bash -c "bin/splunk status" | grep 'splunk helpers are running22'
#  do
#    echo waiting on splunk
#    sleep 10
#  done
}

function start_docker () {
	docker || apt install -y docker docker.io
  systemctl unmask docker.service
  systemctl unmask docker.sockete
	docker info || (systemctl start docker ; sleep 300)
}

#ifconfig eth1:2 10.55.55.6 netmask 255.255.255.0 up

case ${1} in

	start)
	  start_docker
		start
		;;

	stop)
		docker stop ${CONTAINER_NAME} || echo "${CONTAINER_NAME} not running"
		;;

	rm)
		docker stop ${CONTAINER_NAME} || echo "${CONTAINER_NAME} not running"
		docker rm ${CONTAINER_NAME} || echo "${CONTAINER_NAME} doesn't exist"
		;;

	*)
		echo "Usage: ${1} [start | stop | rm]"
		;;
esac


#sleep 150

#cat /repos/nakadia/Docker/etc/system/local/inputs.conf >> /tmp/splunk/etc/system/local/inputs.conf
#cat /repos/nakadia/Docker/etc/system/default/indexes.conf >> /tmp/splunk/etc/system/default/indexes.conf


#sudo docker exec -i --user splunk splunk /bin/bash -c "bin/splunk restart"

#wait_on_startup
#load_data
#container-alive-monitor ${CONTAINER_NAME}


#  docker run -d -p 8000:8000 -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=<password>" --name splunk splunk/splunk:latest